// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhxP9X5gpoJQDi_6oxabDcGQajAG5IcT4',
    appId: '1:944685718677:web:1007af4bcacb0a090f8f9c',
    messagingSenderId: '944685718677',
    projectId: 'project1-fe7e6',
    authDomain: 'project1-fe7e6.firebaseapp.com',
    storageBucket: 'project1-fe7e6.appspot.com',
    measurementId: 'G-6J3EE536PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51MzxFA90oeWTuo6FpJEU6k44yXTqtYM',
    appId: '1:944685718677:android:04ef5b881ecaac6e0f8f9c',
    messagingSenderId: '944685718677',
    projectId: 'project1-fe7e6',
    storageBucket: 'project1-fe7e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfj-ez4O80Fbe7cdchKyJWg0fieuzUVk',
    appId: '1:944685718677:ios:2b077ea2f38c662c0f8f9c',
    messagingSenderId: '944685718677',
    projectId: 'project1-fe7e6',
    storageBucket: 'project1-fe7e6.appspot.com',
    iosClientId: '944685718677-gq2v3a2msm6aven4n8gh2inrpleovl2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBfj-ez4O80Fbe7cdchKyJWg0fieuzUVk',
    appId: '1:944685718677:ios:2b077ea2f38c662c0f8f9c',
    messagingSenderId: '944685718677',
    projectId: 'project1-fe7e6',
    storageBucket: 'project1-fe7e6.appspot.com',
    iosClientId: '944685718677-gq2v3a2msm6aven4n8gh2inrpleovl2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
